#!/usr/bin/env python3
"""
Load Rich ML Concepts from JSONL to MilvusDB
This script loads the rich educational content generated by generate_dataset.py
"""

import os
import json
import sys
from dotenv import load_dotenv

# Fix SSL certificates for Python
os.environ['SSL_CERT_FILE'] = '/etc/ssl/cert.pem'
os.environ['REQUESTS_CA_BUNDLE'] = '/etc/ssl/cert.pem'

# Add the current directory to Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Import RAG system
from rag_system import RAGSystem

# Load environment variables
load_dotenv()

def load_jsonl_data(filepath):
    """Load rich content from JSONL file"""
    concepts = []
    if not os.path.exists(filepath):
        print(f"❌ {filepath} not found")
        return concepts
    
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    record = json.loads(line)
                    concepts.append(record)
                except json.JSONDecodeError:
                    continue
    
    return concepts

def convert_to_milvus_format(jsonl_concepts):
    """Convert JSONL format to Milvus-compatible format"""
    milvus_concepts = []
    
    for record in jsonl_concepts:
        concept = {
            "concept": record["concept_title"],
            "category": f"ML Concepts - {record['slice'].title()}",
            "definition": record["text"],
            "child_analogy": record["text"] if record["slice"] == "analogy" else f"Think of {record['concept_title']} as a helpful tool in machine learning.",
            "real_world_example": record["text"] if record["slice"] == "example" else f"{record['concept_title']} is used in many AI applications.",
            "difficulty": "beginner",
            "keywords": record["tags"] + [record["concept_slug"].replace("-", " ")]
        }
        milvus_concepts.append(concept)
    
    return milvus_concepts

def main():
    """Main function to load rich concepts to MilvusDB"""
    print("🚀 Loading Rich ML Concepts to MilvusDB")
    print("=" * 60)
    
    # Check if JSONL file exists
    jsonl_file = "ml_analogies.jsonl"
    if not os.path.exists(jsonl_file):
        print(f"❌ {jsonl_file} not found!")
        print("💡 Run generate_dataset.py first to create rich content")
        return
    
    # Load rich content
    print(f"📚 Loading rich content from {jsonl_file}...")
    jsonl_concepts = load_jsonl_data(jsonl_file)
    
    if not jsonl_concepts:
        print("❌ No concepts found in JSONL file")
        return
    
    print(f"✅ Loaded {len(jsonl_concepts)} rich content chunks")
    
    # Convert to Milvus format
    print("🔄 Converting to Milvus format...")
    milvus_concepts = convert_to_milvus_format(jsonl_concepts)
    print(f"✅ Converted {len(milvus_concepts)} concepts for Milvus")
    
    # Initialize RAG system
    print("🔌 Connecting to MilvusDB...")
    try:
        rag = RAGSystem()
        current_count = rag.collection.num_entities if rag.collection else 0
        print(f"📊 Current concepts in MilvusDB: {current_count}")
        
        if current_count > 0:
            print(f"\n⚠️  WARNING: This will REPLACE {current_count} existing concepts!")
            print(f"💡 New rich content: {len(milvus_concepts)} concepts")
            
            response = input("\n🤔 Continue? (yes/no): ").lower().strip()
            if response not in ['yes', 'y']:
                print("❌ Operation cancelled")
                return
        
        # Load rich content to Milvus
        print("\n🚀 Loading rich content to MilvusDB...")
        
        # Use the updated force_repopulate with custom concepts
        success = rag.force_repopulate(custom_concepts=milvus_concepts)
        
        if success:
            print("✅ Successfully loaded rich content to MilvusDB!")
            print(f"📊 Total concepts: {len(milvus_concepts)}")
            print("\n💡 Next steps:")
            print("   1. Test with: python test_rag_retrieval.py")
            print("   2. Start your chat application")
        else:
            print("⚠️ Could not load new content, using existing concepts")
        
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    main()
