[project]
name = "rag-vercel-example"
version = "0.1.0"
description = "AI Bootcamp Capstone Project - RAG system deployed on Vercel"
authors = [
    {name = "Santosh Edulapalle", email = ""}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn",
    "openai",
    "python-dotenv",
    "mmh3",
    "requests",
    "jinja2",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "black",
    "flake8",
] 